CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR (255) UNIQUE NOT NULL,
    password VARCHAR (225) NOT NULL
);

CREATE TABLE workouts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    type VARCHAR (255) NOT NULL,
    difficulty VARCHAR (255) NOT NULL
);

CREATE TABLE exercises (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workout_id INTEGER
        REFERENCES workouts(id) ON DELETE CASCADE NOT NULL,
    name VARCHAR (255) NOT NULL,
    image VARCHAR (255) NOT NULL,
    description VARCHAR (255) NOT NULL,
    sets VARCHAR (255) NOT NULL,
    rest VARCHAR (255) NOT NULL,
    is_upper INTEGER DEFAULT 0 NOT NULL,
    is_lower INTEGER DEFAULT 0 NOT NULL,
    is_beginner INTEGER DEFAULT 0 NOT NULL,
    is_intermediate INTEGER DEFAULT 0 NOT NULL,
    is_advanced INTEGER DEFAULT 0 NOT NULL
);

INSERT INTO public.exercises (workout_id,"name",image,description,"sets",rest,is_upper,is_lower,is_beginner,is_intermediate,is_advanced) VALUES 
(3,'Bench Press','image.jpg','The bench press is an upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench','3','60 Seconds',1,0,0,1,0)
,(3,'Lat Pull','image.jpg','The pulldown exercise is a strength training exercise designed to develop the latissimus dorsi muscle.','3','60 Seconds',1,0,0,1,0)
,(3,'Overhead Press','image.jpg','The overhead press (abbreviated OHP) or shoulder press is a weight training exercise performed while standing, in which a weight is pressed straight upwards from racking position until the arms are locked out overhead.','3','60 Seconds',1,0,0,1,0)
,(3,'Pullover','image.jpg','The pullover is an exercise that is performed with either a dumbbell or a barbell. Pullovers can be made to affect either the chest or the back depending on how wide the grip is (barbell) and the position of the shoulders.','3','60 Seconds',1,0,0,1,0)
,(4,'Dumbbell Bench Press','image.jpg','A bench press performed with dumbbells rather than a barbell','3','60 Seconds',1,0,0,0,1)
,(4,'Pullup','image.jpg','an exercise in which one hangs by the hands from a support (such as a horizontal bar) and pulls oneself up until the chin is level with the bar','3','60 Seconds',1,0,0,0,1)
,(4,'Bent Row','image.jpg','A bent-over row (or barbell row) is a weight training exercise that targets a variety of back muscles.','3','60 Seconds',1,0,0,0,1)
,(4,'Push Press','image.jpg','The push press is similar to the military press; however, the movement is started by a ''push'' from the legs','3','60 Seconds',1,0,0,0,1)
,(7,'Body Weight Squat','image.jpg','Bodyweight squat','3','30 Seconds',0,1,1,0,0)
;

CREATE TABLE exercises_templates (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR (255) NOT NULL,
    image VARCHAR (255) NOT NULL,
    description VARCHAR (255) NOT NULL,
    sets VARCHAR (255) NOT NULL,
    rest VARCHAR (255) NOT NULL,
    is_upper INTEGER DEFAULT 0 NOT NULL,
    is_lower INTEGER DEFAULT 0 NOT NULL,
    is_beginner INTEGER DEFAULT 0 NOT NULL,
    is_intermediate INTEGER DEFAULT 0 NOT NULL,
    is_advanced INTEGER DEFAULT 0 NOT NULL
);
INSERT INTO public.exercises_templates ("name",image,description,"sets",rest,is_upper,is_lower,is_beginner,is_intermediate,is_advanced) VALUES 
('Bench Press','image.jpg','The bench press is an upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench','3','60 Seconds',1,0,0,1,0)
,('Lat Pull','image.jpg','The pulldown exercise is a strength training exercise designed to develop the latissimus dorsi muscle.','3','60 Seconds',1,0,0,1,0)
,('Overhead Press','image.jpg','The overhead press (abbreviated OHP) or shoulder press is a weight training exercise performed while standing, in which a weight is pressed straight upwards from racking position until the arms are locked out overhead.','3','60 Seconds',1,0,0,1,0)
,('Pullover','image.jpg','The pullover is an exercise that is performed with either a dumbbell or a barbell. Pullovers can be made to affect either the chest or the back depending on how wide the grip is (barbell) and the position of the shoulders.','3','60 Seconds',1,0,0,1,0)
,('Dumbbell Bench Press','image.jpg','A bench press performed with dumbbells rather than a barbell','3','60 Seconds',1,0,0,0,1)
,('Pullup','image.jpg','an exercise in which one hangs by the hands from a support (such as a horizontal bar) and pulls oneself up until the chin is level with the bar','3','60 Seconds',1,0,0,0,1)
,('Bent Row','image.jpg','A bent-over row (or barbell row) is a weight training exercise that targets a variety of back muscles.','3','60 Seconds',1,0,0,0,1)
,('Push Press','image.jpg','The push press is similar to the military press; however, the movement is started by a ''push'' from the legs','3','60 Seconds',1,0,0,0,1)
,('Body Weight Squat','image.jpg','Bodyweight squat','3','30 Seconds',0,1,1,0,0)
;